# Generated by Django 5.0.7 on 2024-08-01 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Online_shop', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default='exid', max_length=255),
            preserve_default=False,
        ),
    ]
