# Generated by Django 5.0.7 on 2024-08-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Online_shop', '0006_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
